### ISSUE TITLE
Ability to update Client Options on the Guzzle Client

### ISSUE THREAD

**Issue by jswinborne** [sergeyfast/eazy-jsonrpc#8]
I am connecting to a JSON-RPC service and used the generator to create my Client. This API requires a header for Authorization, but I don't believe I am able to edit the property $ClientOptions or the $client directly on the BaseJsonRpcClient.  Both properties are private, so I can not adjust the generated client to pass the additional headers that are needed.  Should $ClientOptions be a protected variable instead of private?  Perhaps even make the Guzzle Client a protected variable, so settings can be adjusted as needed?  Or another way would be to pass an optional parameter to the BaseJsonRpcClient constructor to use as the ClientOptions for the Guzzle Client.  My apologizes if I missed an obvious answer to this problem.  But I can't see a way to pass custom headers to the Guzzle Client.

**Comment by sas1024** [comment]
Hello @jswinborne !
You're right.
I make `$ClientOptions` public, v3.0.2 released.
